"""Structured, read-only presentation of the solver's existing trace records."""

from __future__ import annotations

import tkinter as tk
from dataclasses import dataclass, field
from enum import StrEnum
from tkinter import ttk

from agent.deduction_trace import DeductionTraceStep, SATQueryTrace
from gui.theme import COLORS, FONTS, SPACING


class ActionSource(StrEnum):
    """Reliable controller-owned metadata for newly appended trace steps."""

    HINT = "HINT"
    MANUAL_VERDICT = "MANUAL VERDICT"
    SOLVE_NEXT = "SOLVE NEXT"
    AUTO_SOLVE = "AUTO SOLVE"


@dataclass(frozen=True, slots=True)
class SATQueryPresentation:
    purpose: str
    assumption: str | None
    result: str
    decisions: int
    propagations: int
    backtracks: int
    runtime: float


@dataclass(frozen=True, slots=True)
class TraceStepPresentation:
    step_number: int
    target: str | None
    verdict: str
    active_clue_ids: tuple[str, ...]
    sat_queries: tuple[SATQueryPresentation, ...]
    newly_revealed_clue: str | None
    source: ActionSource | None = None


def _query_presentation(query: SATQueryTrace) -> SATQueryPresentation:
    return SATQueryPresentation(
        purpose=query.purpose,
        assumption=query.assumption.value if query.assumption is not None else None,
        result=query.result,
        decisions=query.decisions,
        propagations=query.propagations,
        backtracks=query.backtracks,
        runtime=query.runtime,
    )


def build_trace_presentations(
    steps: tuple[DeductionTraceStep, ...],
    sources: dict[int, ActionSource] | None = None,
) -> tuple[TraceStepPresentation, ...]:
    """Copy only fields explicitly exposed by the solver trace contract."""

    source_map = sources or {}
    return tuple(
        TraceStepPresentation(
            step_number=step.step_number,
            target=step.character_id,
            verdict=step.verdict.value,
            active_clue_ids=step.active_clue_ids,
            sat_queries=tuple(_query_presentation(query) for query in step.sat_queries),
            newly_revealed_clue=step.newly_revealed_clue,
            source=source_map.get(step.step_number),
        )
        for step in steps
    )


@dataclass(slots=True)
class SolverDetailsModel:
    """Presentation-only visibility and reliable action-source bookkeeping."""

    is_open: bool = False
    _sources: dict[int, ActionSource] = field(default_factory=dict)

    def open(self) -> None:
        self.is_open = True

    def close(self) -> None:
        self.is_open = False

    def clear_trace_metadata(self) -> None:
        self._sources.clear()

    def record_new_steps(
        self,
        before_count: int,
        steps: tuple[DeductionTraceStep, ...],
        source: ActionSource,
    ) -> None:
        """Label only the slice known to have been generated by one UI action."""

        if before_count < 0 or before_count > len(steps):
            raise ValueError("before_count must identify a valid trace boundary")
        for step in steps[before_count:]:
            self._sources[step.step_number] = source

    def presentations(
        self, steps: tuple[DeductionTraceStep, ...]
    ) -> tuple[TraceStepPresentation, ...]:
        return build_trace_presentations(steps, self._sources)


class TraceStepCard(ttk.Frame):
    """One human-readable deduction step; no proof text is synthesized."""

    def __init__(self, parent: tk.Misc, step: TraceStepPresentation) -> None:
        super().__init__(parent, style="TraceCard.TFrame", padding=SPACING["md"])
        self.columnconfigure(0, weight=1)

        header = ttk.Frame(self, style="TraceCard.TFrame")
        header.grid(row=0, column=0, sticky="ew")
        header.columnconfigure(1, weight=1)
        ttk.Label(header, text=f"STEP {step.step_number}", style="TraceStep.TLabel").grid(
            row=0, column=0, sticky="w"
        )
        if step.source is not None:
            ttk.Label(header, text=step.source.value, style="TraceSource.TLabel").grid(
                row=0, column=2, sticky="e"
            )

        summary = ttk.Frame(self, style="TraceCard.TFrame")
        summary.grid(row=1, column=0, sticky="ew", pady=(SPACING["sm"], 0))
        summary.columnconfigure(1, weight=1)
        self._field(summary, 0, "TARGET", step.target or "Unavailable")
        self._field(summary, 1, "VERDICT", step.verdict)
        active = ", ".join(step.active_clue_ids) if step.active_clue_ids else "None recorded"
        self._field(summary, 2, "ACTIVE CLUES", active, wraplength=510)
        next_row = 3
        if step.newly_revealed_clue is not None:
            self._field(summary, next_row, "NEWLY REVEALED", step.newly_revealed_clue)
            next_row += 1

        ttk.Separator(summary, orient="horizontal").grid(
            row=next_row, column=0, columnspan=2, sticky="ew", pady=(SPACING["sm"], SPACING["xs"])
        )
        ttk.Label(
            summary,
            text=f"SAT QUERIES · {len(step.sat_queries)} · statistics are per query",
            style="TraceSection.TLabel",
        ).grid(row=next_row + 1, column=0, columnspan=2, sticky="w")

        query_row = next_row + 2
        if not step.sat_queries:
            ttk.Label(summary, text="No SAT query data recorded.", style="TraceValue.TLabel").grid(
                row=query_row, column=0, columnspan=2, sticky="w", pady=(SPACING["xs"], 0)
            )
        for index, query in enumerate(step.sat_queries, start=1):
            query_card = ttk.Frame(summary, style="TraceQuery.TFrame", padding=(SPACING["sm"], 6))
            query_card.grid(row=query_row, column=0, columnspan=2, sticky="ew", pady=(SPACING["xs"], 0))
            query_card.columnconfigure(1, weight=1)
            ttk.Label(
                query_card,
                text=f"QUERY {index} · {query.purpose}",
                style="TraceQueryTitle.TLabel",
            ).grid(row=0, column=0, columnspan=2, sticky="w")
            row = 1
            if query.assumption is not None:
                self._query_field(query_card, row, "Assumption", f"{step.target or 'target'} is {query.assumption}")
                row += 1
            self._query_field(query_card, row, "Result", query.result)
            row += 1
            metrics = (
                f"decisions {query.decisions}  ·  propagations {query.propagations}  ·  "
                f"backtracks {query.backtracks}  ·  runtime {query.runtime:.6f}s"
            )
            self._query_field(query_card, row, "Statistics", metrics)
            query_row += 1

    @staticmethod
    def _field(
        parent: tk.Misc,
        row: int,
        label: str,
        value: str,
        *,
        wraplength: int = 540,
    ) -> None:
        ttk.Label(parent, text=label, style="TraceField.TLabel").grid(
            row=row, column=0, sticky="nw", padx=(0, SPACING["md"]), pady=2
        )
        ttk.Label(
            parent,
            text=value,
            style="TraceValue.TLabel",
            wraplength=wraplength,
            justify="left",
        ).grid(row=row, column=1, sticky="nw", pady=2)

    @staticmethod
    def _query_field(parent: tk.Misc, row: int, label: str, value: str) -> None:
        ttk.Label(parent, text=f"{label}:", style="TraceQueryLabel.TLabel").grid(
            row=row, column=0, sticky="nw", padx=(0, SPACING["sm"])
        )
        ttk.Label(
            parent,
            text=value,
            style="TraceQueryValue.TLabel",
            wraplength=470,
            justify="left",
        ).grid(row=row, column=1, sticky="nw")


class SolverDetailsWindow:
    """Secondary Toplevel that preserves board space in normal gameplay."""

    def __init__(self, parent: tk.Misc, model: SolverDetailsModel) -> None:
        self._model = model
        self.window = tk.Toplevel(parent)
        self.window.title("Solver Details · Griductive")
        self.window.configure(background=COLORS["canvas"])
        screen_width = self.window.winfo_screenwidth()
        screen_height = self.window.winfo_screenheight()
        width = min(720, max(580, screen_width - 140))
        height = min(760, max(520, screen_height - 120))
        self.window.geometry(f"{width}x{height}")
        self.window.minsize(min(580, width), min(520, height))
        self.window.protocol("WM_DELETE_WINDOW", self.close)
        self.window.rowconfigure(1, weight=1)
        self.window.columnconfigure(0, weight=1)

        header = ttk.Frame(self.window, style="Header.TFrame", padding=(SPACING["lg"], SPACING["sm"]))
        header.grid(row=0, column=0, sticky="ew")
        header.columnconfigure(0, weight=1)
        ttk.Label(header, text="SOLVER DETAILS", style="SolverDetailsTitle.TLabel").grid(
            row=0, column=0, sticky="w"
        )
        ttk.Label(
            header,
            text="Recorded SAT deductions · read-only technical view",
            style="AppSubtitle.TLabel",
        ).grid(row=1, column=0, sticky="w")
        ttk.Button(header, text="Close", command=self.close, style="Game.TButton").grid(
            row=0, column=1, rowspan=2, sticky="e"
        )

        shell = ttk.Frame(self.window, style="App.TFrame", padding=SPACING["md"])
        shell.grid(row=1, column=0, sticky="nsew")
        shell.rowconfigure(0, weight=1)
        shell.columnconfigure(0, weight=1)
        self._canvas = tk.Canvas(
            shell,
            background=COLORS["canvas"],
            borderwidth=0,
            highlightthickness=0,
        )
        scrollbar = ttk.Scrollbar(shell, orient="vertical", command=self._canvas.yview)
        self._canvas.configure(yscrollcommand=scrollbar.set)
        self._canvas.grid(row=0, column=0, sticky="nsew")
        scrollbar.grid(row=0, column=1, sticky="ns")
        self._content = ttk.Frame(self._canvas, style="App.TFrame")
        self._canvas_window = self._canvas.create_window((0, 0), window=self._content, anchor="nw")
        self._content.bind("<Configure>", self._update_scrollregion)
        self._canvas.bind("<Configure>", self._resize_content)
        self._canvas.bind("<MouseWheel>", self._mousewheel)

    @property
    def exists(self) -> bool:
        return bool(self.window.winfo_exists())

    def open(self) -> None:
        self._model.open()
        self.window.deiconify()
        self.window.lift()

    def close(self) -> None:
        self._model.close()
        self.window.withdraw()

    def render(self, steps: tuple[TraceStepPresentation, ...]) -> None:
        if not self.exists:
            return
        for child in self._content.winfo_children():
            child.destroy()
        self._content.columnconfigure(0, weight=1)
        if not steps:
            empty = ttk.Frame(self._content, style="TraceCard.TFrame", padding=SPACING["xl"])
            empty.grid(row=0, column=0, sticky="ew")
            ttk.Label(empty, text="No solver trace yet", style="TraceStep.TLabel").grid(row=0, column=0)
            ttk.Label(
                empty,
                text="Use Hint Stage 1, submit a verdict, Solve Next, or Auto Solve to generate real trace data.",
                style="TraceValue.TLabel",
                wraplength=500,
                justify="center",
            ).grid(row=1, column=0, pady=(SPACING["sm"], 0))
        last_card: TraceStepCard | None = None
        for row, step in enumerate(steps):
            card = TraceStepCard(self._content, step)
            card.grid(row=row, column=0, sticky="ew", pady=(0, SPACING["sm"]))
            self._bind_mousewheel_tree(card)
            last_card = card
        self._content.update_idletasks()
        self._update_scrollregion()
        if last_card is not None:
            content_height = self._content.winfo_height()
            if content_height > self._canvas.winfo_height():
                self._canvas.yview_moveto(last_card.winfo_y() / content_height)

    def _update_scrollregion(self, _event: tk.Event | None = None) -> None:
        self._canvas.configure(scrollregion=self._canvas.bbox("all"))

    def _resize_content(self, event: tk.Event) -> None:
        self._canvas.itemconfigure(self._canvas_window, width=event.width)

    def _mousewheel(self, event: tk.Event) -> None:
        self._canvas.yview_scroll(-1 if event.delta > 0 else 1, "units")

    def _bind_mousewheel_tree(self, widget: tk.Misc) -> None:
        widget.bind("<MouseWheel>", self._mousewheel, add="+")
        for child in widget.winfo_children():
            self._bind_mousewheel_tree(child)
